sudo: required

language: php

php:
  - '7.0'

branches:
  only:
    - master
    - develop

services:
  - docker

install:
  - composer install --no-scripts

before_script:
  - wget https://alg.li/algolia-keys && chmod +x algolia-keys

script:
  - eval $(./algolia-keys export) && dev/runTests.sh -a $ALGOLIA_APPLICATION_ID -k $ALGOLIA_API_KEY -s $ALGOLIA_SEARCH_API_KEY -b http://magento.local -p TRAVIS_M1_ -v 193
